USE [master]
GO
/****** Object:  Database [DATAMART_NORTHWIND]    Script Date: 28/03/2025 02:44:02 p. m. ******/
CREATE DATABASE [DATAMART_NORTHWIND]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DATAMART_NORTHWIND', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.ADRIAN\MSSQL\DATA\DATAMART_NORTHWIND.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DATAMART_NORTHWIND_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.ADRIAN\MSSQL\DATA\DATAMART_NORTHWIND_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DATAMART_NORTHWIND].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET ARITHABORT OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET RECOVERY FULL 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET  MULTI_USER 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DATAMART_NORTHWIND', N'ON'
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET QUERY_STORE = ON
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [DATAMART_NORTHWIND]
GO
/****** Object:  Table [dbo].[Dim_Cliente]    Script Date: 28/03/2025 02:44:02 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Cliente](
	[Cliente_Skey] [int] IDENTITY(1,1) NOT NULL,
	[Cliente_CodigoBKey] [char](5) NOT NULL,
	[Cliente_Nombre] [varchar](40) NOT NULL,
	[Cliente_Compañia] [varchar](40) NOT NULL,
	[Cliente_Direccion] [varchar](60) NOT NULL,
	[Cliente_Ciudad] [varchar](15) NOT NULL,
	[Cliente_Region] [varchar](25) NOT NULL,
	[Cliente_Pais] [varchar](15) NOT NULL,
 CONSTRAINT [PK_Dim_Cliente] PRIMARY KEY CLUSTERED 
(
	[Cliente_Skey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dim_Empleado]    Script Date: 28/03/2025 02:44:02 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Empleado](
	[Empleado_Skey] [int] IDENTITY(1,1) NOT NULL,
	[Empleado_Codigo] [int] NOT NULL,
	[Empleado_NombreCompleto] [varchar](75) NOT NULL,
	[Empleado_Direccion] [varchar](120) NOT NULL,
	[Empleado_Ciudad] [varchar](15) NOT NULL,
	[Empleado_Region] [varchar](15) NOT NULL,
	[Empleado_Pais] [varchar](15) NOT NULL,
 CONSTRAINT [PK_Dim_Empleado] PRIMARY KEY CLUSTERED 
(
	[Empleado_Skey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dim_Producto]    Script Date: 28/03/2025 02:44:02 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Producto](
	[Producto_Skey] [int] IDENTITY(1,1) NOT NULL,
	[Producto_Codigo_Bkey] [int] NOT NULL,
	[Producto_Nombre] [varchar](80) NOT NULL,
	[Producto_Categoria_Nombre] [varchar](15) NOT NULL,
	[Producto_Proveedor_Nombre] [varchar](40) NOT NULL,
 CONSTRAINT [PK_Dim_Producto] PRIMARY KEY CLUSTERED 
(
	[Producto_Skey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dim_Tiempo]    Script Date: 28/03/2025 02:44:02 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Tiempo](
	[Tiempo_Skey] [int] IDENTITY(1,1) NOT NULL,
	[Tiempo_FechaActual] [datetime] NOT NULL,
	[Tiempo_Anio] [int] NOT NULL,
	[Tiempo_Trimestre] [int] NOT NULL,
	[Tiempo_Mes] [int] NOT NULL,
	[Timepo_Semana] [int] NOT NULL,
	[Tiempo_DiaDeAnio] [int] NOT NULL,
	[Tiempo_DiaDeMes] [int] NOT NULL,
	[Tiempo_DiaDeSemana] [int] NOT NULL,
 CONSTRAINT [PK_Dim_Tiempo] PRIMARY KEY CLUSTERED 
(
	[Tiempo_Skey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Fact_Ventas]    Script Date: 28/03/2025 02:44:02 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Fact_Ventas](
	[Cliente_Skey] [int] NOT NULL,
	[Empleado_Skey] [int] NOT NULL,
	[Producto_Skey] [int] NOT NULL,
	[Tiempo_SKey] [int] NOT NULL,
	[Ventas_Monto] [decimal](15, 2) NOT NULL,
	[Ventas_Unidades] [int] NOT NULL,
	[Ventas_PUnitario] [decimal](15, 2) NOT NULL,
	[Ventas_Descuento] [decimal](15, 2) NOT NULL,
 CONSTRAINT [PK_Fact_Ventas] PRIMARY KEY CLUSTERED 
(
	[Cliente_Skey] ASC,
	[Empleado_Skey] ASC,
	[Producto_Skey] ASC,
	[Tiempo_SKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Fact_Ventas]  WITH CHECK ADD  CONSTRAINT [FK_Fact_Ventas_Dim_Cliente] FOREIGN KEY([Cliente_Skey])
REFERENCES [dbo].[Dim_Cliente] ([Cliente_Skey])
GO
ALTER TABLE [dbo].[Fact_Ventas] CHECK CONSTRAINT [FK_Fact_Ventas_Dim_Cliente]
GO
ALTER TABLE [dbo].[Fact_Ventas]  WITH CHECK ADD  CONSTRAINT [FK_Fact_Ventas_Dim_Empleado] FOREIGN KEY([Empleado_Skey])
REFERENCES [dbo].[Dim_Empleado] ([Empleado_Skey])
GO
ALTER TABLE [dbo].[Fact_Ventas] CHECK CONSTRAINT [FK_Fact_Ventas_Dim_Empleado]
GO
ALTER TABLE [dbo].[Fact_Ventas]  WITH CHECK ADD  CONSTRAINT [FK_Fact_Ventas_Dim_Producto] FOREIGN KEY([Producto_Skey])
REFERENCES [dbo].[Dim_Producto] ([Producto_Skey])
GO
ALTER TABLE [dbo].[Fact_Ventas] CHECK CONSTRAINT [FK_Fact_Ventas_Dim_Producto]
GO
ALTER TABLE [dbo].[Fact_Ventas]  WITH CHECK ADD  CONSTRAINT [FK_Fact_Ventas_Dim_Tiempo] FOREIGN KEY([Tiempo_SKey])
REFERENCES [dbo].[Dim_Tiempo] ([Tiempo_Skey])
GO
ALTER TABLE [dbo].[Fact_Ventas] CHECK CONSTRAINT [FK_Fact_Ventas_Dim_Tiempo]
GO
USE [master]
GO
ALTER DATABASE [DATAMART_NORTHWIND] SET  READ_WRITE 
GO
